# Generated by Django 4.2.6 on 2023-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(null=True, upload_to="pictures"),
        ),
    ]
