# Generated by Django 4.2.6 on 2023-10-31 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0002_picture_author_picture_name_alter_picture_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="name",
            new_name="picture_name",
        ),
    ]
