# Generated by Django 4.2.6 on 2023-10-31 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0003_rename_name_picture_picture_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="picture_name",
            new_name="name",
        ),
    ]
