# Generated by Django 4.2.6 on 2023-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0005_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("picture", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "music_list",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MetawavePicture",
        ),
    ]
