# Generated by Django 4.2.6 on 2023-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0007_remove_picture_author_remove_picture_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"managed": False},
        ),
    ]
