# Generated by Django 4.2.6 on 2023-11-03 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0008_alter_picture_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="picture",
            table="picture",
        ),
    ]
