# Generated by Django 4.2.6 on 2023-11-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0009_alter_picture_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="inputPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("picture", models.ImageField(null=True, upload_to="pictures")),
            ],
            options={
                "db_table": "picture",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="picture",
        ),
    ]
