# Generated by Django 4.2.6 on 2023-11-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0010_inputpicture_delete_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodthemePlaylist",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        blank=True, db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "track_id",
                    models.TextField(blank=True, db_column="TRACK_ID", null=True),
                ),
                (
                    "artist_id",
                    models.TextField(blank=True, db_column="ARTIST_ID", null=True),
                ),
                (
                    "album_id",
                    models.TextField(blank=True, db_column="ALBUM_ID", null=True),
                ),
                ("path", models.TextField(blank=True, db_column="PATH", null=True)),
                (
                    "duration",
                    models.FloatField(blank=True, db_column="DURATION", null=True),
                ),
                ("tags", models.TextField(blank=True, db_column="TAGS", null=True)),
            ],
            options={
                "db_table": "moodtheme_playlist",
                "managed": False,
            },
        ),
    ]
