# Generated by Django 4.2.6 on 2023-11-15 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0011_moodthemeplaylist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MusicList",
        ),
    ]
