# Generated by Django 4.2.6 on 2023-11-22 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metawave",
            "0013_picture_delete_authgroup_delete_authgrouppermissions_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Picture",
            new_name="Pictures",
        ),
    ]
