# Generated by Django 4.2.6 on 2023-11-22 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metawave", "0014_rename_picture_pictures"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pictures",
            new_name="Picture",
        ),
    ]
